routes:
  /: home
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /abbonamenti/: members/membership
  /numeri/: issues

collections:
  /blog/:
    permalink: /blog/{slug}/
    filter: tag:blog+tag:-rivista
    template: index
    data: 
      post: page.blog
  /rivista/:
    permalink: /rivista/{slug}/
    filter: tag:rivista+tag:-blog
    template: index
    data:
      post: page.rivista

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
